# Languages https://docs.travis-ci.com/user/languages/java/
language: java
jdk:
  - oraclejdk11

sudo: required
dist: trusty

addons: # get google-chrome-stable
  chrome: stable
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 

install: 
    - wget -N http://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip -P ~/
    - unzip ~/chromedriver_linux64.zip -d ~/
    - rm ~/chromedriver_linux64.zip
    - sudo mv -f ~/chromedriver /usr/local/share/
    - sudo chmod +x /usr/local/share/chromedriver


deploy:
  provider: releases
  api_key: nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA5Py2NLP8O8iVc+BDkrVd\nSmMrbtv7q2zKPw57E/5SAVXkmK2/6f3QZwhyWF+42duvmc8M7NmeZqoWx7Q1oZlR\ncKhY3jK8KcwFIKEcA8gaRdXDCP7DDkdlBhDJsqYDkVTM21beaT5AXmU+FJGTH0YE\nkRQ8jy8sRI0kObp36a852g9S0XnwqseFVjBvtJFb87YLxTcxOVyYtonZMnb7qD6p\nl5TzjtRnFfljalncZx/ASFHpq2mE3y3y1if7wUNJXrU91CuqHcYJ504VkaXGLWAZ\nZjWPMvhiPMfCig3MCkw7Lqww4SUO2IaFJyut3gyRQxfDcIeF7PW3F+0zd2RFBDFf\nDxhm/1CNo/5bVrZ3YRi0+1vFa8Y+fAMoyS3S69MtLDEzUu0kvpTQHuGSPYCf6onD\nMgojNRclfPnm4M9rzm/1JcwjVum/4KtAOEX9piGlG/4QGF/eXC81WIx5+LyjJtM+\nNegXpPoWxFxrEU5lNAL/iZMoyepHiPaRCUgpa5HUKRu25u0fQ8cq0e5aAOpRuo+x\nSbh35bJjly5s7S1cdK6Ze7jVRUWGn/gJdwgGgEnaSrg1NSSG2QkiNgsdc4HJele3\ndlzglh90VW+1Kjc1gSd/3Xnsqw0/wb7rbVJKniV//e9tRJ+rSgEDuRnCCC74ud4F\nYU1XpzKJbz+x+ZLq1/AWFB0CAwEAAQ==
  file: src/*
  skip_cleanup: true
  on:
    tags: false
    branches: master

# Improve Build Speed https://dzone.com/articles/travis-ci-tutorial-java-projects
cache:
  directories:
  - $HOME/.m2

# Codecov https://github.com/codecov/example-java
after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
  - CODECOV_TOKEN="429f7dbf-9c98-41aa-87d3-8c14e0e07703"
