language: java
before_install: cd LR/03
branches:
  only:
  - master
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  edge: true
- provider: script
  script: ./create-release.sh
  token: $GITHUB_TOKEN
  cleanup: true 



