language: java
before_install: cd LR/03
branches:
  only:
  - master
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:  
      VERSION_TAG="v`cat VERSION.txt`"
    - git tag $TRAVIS_TAG
deploy:
  edge: true
  token: $GITHUB_TOKEN
  cleanup: true
  provider: releases
  prerelease: true
  name: TPRO
