language: java
before_install: cd LR/03
branches:
  only:
  - master
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  edge: true
  token: $GITHUB_TOKEN
  cleanup: true
  provider: releases
  prerelease: true
  tags: true
  name: TPRO
