language: java
branches:
  only:
  - master
jdk:
- oraclejdk11
sudo: required
dist: trusty

script:
  -cd SeleniumIntegrationTest

cache:
  directories:
  - "$HOME/.m2"
after_success:
- bash <(curl -s https://codecov.io/bash)



   



