language: java
before_install: cd LR/03
branches:
  only:
  - master
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:  
    - cd ../../
    - TAG="v`cat VERSION.txt`"
    - git tag $TAG
    - TAG=$`cat VERSION.txt`
    - $TAG+$(0.0.1)
    - echo $a > <VERSION.txt>
deploy:
  edge: true
  token: $GITHUB_TOKEN
  cleanup: true
  provider: releases
  prerelease: true
  name: TPRO
