language: java
before_install: cd LR/03
branches:
  only:
  - master
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:  
    - cd ../../
    - TAG="v0.0.0."$VERSION
    - git tag $TAG
    - echo "VERSION = $VERSION++" 
deploy:
  edge: true
  token: $GITHUB_TOKEN
  cleanup: true
  provider: releases
  prerelease: true
  name: TPRO
