language: java
branches:
  only:
  - master
jdk:
- oraclejdk11
sudo: required
dist: trusty
addons:
  chrome: stable
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script: mvn install


install:
- wget -N http://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip
  -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/share/
- sudo chmod +x /usr/local/share/chromedriver
cache:
  directories:
  - "$HOME/.m2"
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:
  # Following line creates a tag name "v0" if no "v*" tag exist, or a tag "vN+1" if the largest version tag is "vN"
  - ({ echo v0 ; git tag -l v* --sort=v:refname ; }) | cat
  - export TRAVIS_TAG="v$(echo "$({ echo v0 ; git tag -l v* --sort=v:refname ; } | tail -n 1 | tr -d v) + 1" | bc)"
  - echo "TRAVIS_TAG"=$TRAVIS_TAG
deploy:
  skip_cleanup: true
  provider: releases
  prerelease: true
  name: 18-VTbo-1b

  api_key:
    secure: 1vSiEA6SvlH8xptEZkgMSfCURkAnqjKoixlhhnCl+cUAnEtA0JDEj8KJz1ql2aD2hgS4RrBESAJjVW+XH6XahyBPZsY6+ecNhmuWpcSiRQLg5er7rJbscWCpzUwZ/vNh0zWIWgjCUHgy+Y18sSOguwBunTPdkMGEsI53ox/iaZbreVenPXH1vp2zHhN4N9QWafjX/e4JnAgwMdjD56xHEKE2RaMf1azBFhbU/ZM81cOB7K+WS6+b+8cHeX+z7dpGahOetqMKQmnu96utGYipR9+VYH7MFU0zR3TJOhMe7FcEHzFKv5HdwCohRv+ajI6ZoeEvWu58/hdA+VPS+2Iud5NK3CFJkMu8MgRrhcpEKfhceZxwRa6TMo8g/kRG6V2ePtmsJBQpQ0+D+iboGEQ3gLCJxfpdaY7EJWphRRLHWYHB2COtBb4oJPsV6UrDVVW1GwwArXHsYlORazYrESLbT2WNVUaafhxkh9QmCEenK4z4cePP00EXFeK3+i2lD+Bhv8oilj5k76hatiSQkFCybnZf/F6u8nt8jNT+IjvQ6+sTJMtS8AiwItJ9T3DeQO7FKU5wswPxCnto1GfbSwrm0O1wT+8LZynMcQ8s3Uc2vzY9+ZDOAZMvFn/Is3gGJK4p75ceLdIrb3M4+L3+Q6co/0Ehd9SckujjdT8CNirNaH0=
  file: 
     - /home/travis/build/DanilKozlov00/SeleniumIntegrationTest/target/Selen-0.1-jar-with-dependencies.jar
     - /home/travis/build/DanilKozlov00/SeleniumIntegrationTest/Repository.xml
     
  on:
    repo: DanilKozlov00/SeleniumIntegrationTest
after_deploy:
  - git tag $TRAVIS_TAG
   



