language: java
jdk:
- oraclejdk11
sudo: required
dist: trusty
addons:
  chrome: stable
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
install:
- wget -N http://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip
  -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/share/
- sudo chmod +x /usr/local/share/chromedriver
cache:
  directories:
  - "$HOME/.m2"
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  api_key:
    secure: UjgtRluvM2zzBx3FX+Iejj2lq+beaPDOuKLuuB720PuuUOhG4bZkkUyx4Ddbs0N0qLQV49i5Loc5yRaXjToNSAmya35La1JqcqmR5aGuOHD+YDfIrI/7D93UQuBK6ANCEw5e/RKf0naY6yf/MFbmGXSayjJ0inXq8ncIHoPpg6MJDsJoYTQ0TDg8LgddPwUI0Dbxu+9x8pZlieNXEYg1/xS+sTwzoQvo5PURldC+cwDIuweS/4HUKK8wJQB0TDOsis66HsNpHX0okG7JEXkLtiMLSzJRmfxutVPjWj8pVJ4uJuXo5IxmxHSUxI47SfG0KkcU2+MMn1WNYVOkD7jQpZnvS+t6YPYrosh6y7WG4DtijAaxazEZJSC3PxWH26S7usf3k5NihLOjP+appyiXAyJmg3TuPM6wwzhnzFOsYnbICvNWjy3WAlV1wAxRehu+5NwF8LG39lZ/+c8uj/x3duUavYrVA7AP0fuOCF7Fu0l4MpKTz554n6hk30r+7KBmEidoY6786pR/TBp8I41lr3kRHf4ON2HI5fwho87bJDb/zT358S8m3F2lzgbWTrK+mEeeBM4EPLmXLJOwqWPY5vb5Gnnwxpba3BSdgUfC6jKgZhtnGNtLPDmvpfTpjL93DQH9w6k1dgosWlAXr1B5C/cQ5F7XlYoh3KGYxEDyeNU=
  file: pom.xml
  on:
    repo: DanilKozlov00/SeleniumIntegrationTest
