language: java
before_install: cd LR/03
branches:
  only:
  - master
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:  
    - git fetch --tags
    - TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
    - IFS='.' read -ra my_array <<< "$TAG"
    - NUMBER="${my_array[3]}"
    - NUMBER="$((NUMBER+1))"
    - TAG=v0.0.0.$NUMBER
    - git tag $TAG
    - mkdir Project
    - cd /home/travis/build/DanilKozlov00/SeleniumIntegrationTest/LR/03/target
    - mv Selen-0.1-jar-with-dependencies.jar home/travis/build/DanilKozlov00/SeleniumIntegrationTest/
    - cd ../
    - mv Repository.xml home/travis/build/DanilKozlov00/SeleniumIntegrationTest/t
    - cd ../../
    - mv VERSION.txt home/travis/build/DanilKozlov00/SeleniumIntegrationTest/Project
    - zip Project.zip Project

deploy:
  edge: true
  token: $GITHUB_TOKEN
  cleanup: true
  provider: releases
  prerelease: true
  name: TPRO

