dist: trusty
sudo: required
matrix:
  include:
    - language: java
      jdk: oraclejdk11
      before_install:
        - cd LR/03
      addons:
        chrome: stable
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3
      script:
        - mvn install
      install:
        - wget -N http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
          -P ~/
        - unzip ~/chromedriver_linux64.zip -d ~/
        - rm ~/chromedriver_linux64.zip
        - sudo mv -f ~/chromedriver /usr/local/share/
        - sudo chmod +x /usr/local/share/chromedriver
      cache:
        directories:
          - "$HOME/.m2"
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - language: cpp
      os: linux
      compiler: gcc
      cache: ccache
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      before_install:
        - export PATH="/usr/lib/ccache:$PATH"
        - CC=gcc-7 && CXX=g++-7
      install:
        - sudo apt-get install -y qt5-default qttools5-dev-tools
        - sudo apt-get install mesa-common-dev
        - sudo apt-get install libgl1-mesa-dev
        - chmod ugo+x LR/07/tests/getTestSuites/downloadTestSuites.sh
        - LR/07/tests/getTestSuites/downloadTestSuites.sh
      after_script:
        - make clean
      before_script: cd LR/07/tests
      script:
        - sudo qmake tests.pro && make
        - sudo ./tests
    - stage: deploy
      language: java
      jdk: oraclejdk11
      before_install:
        - cd LR/03
        - sudo apt-get install rar
      addons:
        chrome: stable
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3
      script: mvn install -DskipTests
      install:
        - wget -N http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
          -P ~/
        - unzip ~/chromedriver_linux64.zip -d ~/
        - rm ~/chromedriver_linux64.zip
        - sudo mv -f ~/chromedriver /usr/local/share/
        - sudo chmod +x /usr/local/share/chromedriver
      cache:
        directories:
          - "$HOME/.m2"
      deploy:
        edge: true
        token: $GITHUB_TOKEN
        cleanup: false
        provider: releases
        draft: true
        file:
          - /home/travis/build/DanilKozlov00/SeleniumIntegrationTest/pom.xml
        prerelease: true
        name: TPRO
        tag_name: "$TRAVIS_TAG"
          on:
            tags: true
          edge: true
    - stage: deploy2
      language: cpp
      os: linux
      compiler: gcc
      cache: ccache
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      before_install:
        - export PATH="/usr/lib/ccache:$PATH"
        - CC=gcc-7 && CXX=g++-7
      install:
        - sudo apt-get install -y qt5-default qttools5-dev-tools
        - sudo apt-get install mesa-common-dev
        - sudo apt-get install libgl1-mesa-dev
        - chmod ugo+x LR/07/tests/getTestSuites/downloadTestSuites.sh
        - LR/07/tests/getTestSuites/downloadTestSuites.sh
      after_script:
        - make clean
      before_script: cd LR/07/src
      script:
        - sudo qmake src.pro && make
      before_deploy:
        - git fetch --tags
        - TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        - IFS='.' read -ra my_array <<< "$TAG"
        - NUMBER="${my_array[3]}"
        - NUMBER="$((NUMBER+1))"
        - TAG=v0.0.0.$NUMBER
        - git tag $TAG
      deploy:
        edge: true
        token: $GITHUB_TOKEN
        cleanup: false
        provider: releases
        file:
          - /home/travis/build/DanilKozlov00/SeleniumIntegrationTest/LR/07/src/main.cpp
        prerelease: true
        name: TPRO
      